#!/bin/bash
# Feishu Interactive Card Notify Script for Claude Code Hooks
# This file is auto-generated by install-claude-notify-hooks skill.

WEBHOOK_URL="__FEISHU_WEBHOOK_URL__"
EVENT_TYPE="${1:-Stop}"

# Read stdin JSON from Claude Code hook
STDIN_JSON=$(cat)

# Delegate to Python for UTF-8 safe JSON building and sending
py -3 -c "
import sys, json, urllib.request

webhook_url = '${WEBHOOK_URL}'
event_type = '${EVENT_TYPE}'
stdin_json = sys.stdin.read() if not sys.stdin.isatty() else '{}'

try:
    data = json.loads(stdin_json) if stdin_json.strip() else {}
except:
    data = {}

session_id = data.get('session_id', 'N/A')
cwd = data.get('cwd', 'N/A')
reason = data.get('reason', '')
permission_mode = data.get('permission_mode', 'N/A')
hook_event = data.get('hook_event_name', event_type)

import os
project_name = os.path.basename(cwd) if cwd != 'N/A' else 'N/A'
short_session_id = session_id[:8] if len(session_id) > 8 else session_id

if hook_event == 'Notification':
    theme_color = 'orange'
    title = '⏳ Claude Code 需要确认'
    content = '<at id=all></at> 请回到终端操作'
else:
    theme_color = 'blue'
    title = '\U0001f916 Claude Code 执行完毕'
    content = '<at id=all></at> 请查看执行结果'

if reason:
    content = '<at id=all></at> ' + reason

card = {
    'msg_type': 'interactive',
    'card': {
        'header': {
            'title': {
                'tag': 'plain_text',
                'content': title
            },
            'template': theme_color
        },
        'elements': [
            {
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**' + content + '**'
                }
            },
            {'tag': 'hr'},
            {
                'tag': 'column_set',
                'flex_mode': 'bisect',
                'background_style': 'default',
                'columns': [
                    {
                        'tag': 'column',
                        'width': 'weighted',
                        'weight': 1,
                        'elements': [{
                            'tag': 'div',
                            'text': {
                                'tag': 'lark_md',
                                'content': '**项目**\n' + project_name
                            }
                        }]
                    },
                    {
                        'tag': 'column',
                        'width': 'weighted',
                        'weight': 1,
                        'elements': [{
                            'tag': 'div',
                            'text': {
                                'tag': 'lark_md',
                                'content': '**会话**\n' + short_session_id
                            }
                        }]
                    }
                ]
            },
            {
                'tag': 'column_set',
                'flex_mode': 'bisect',
                'background_style': 'default',
                'columns': [
                    {
                        'tag': 'column',
                        'width': 'weighted',
                        'weight': 1,
                        'elements': [{
                            'tag': 'div',
                            'text': {
                                'tag': 'lark_md',
                                'content': '**权限模式**\n' + permission_mode
                            }
                        }]
                    },
                    {
                        'tag': 'column',
                        'width': 'weighted',
                        'weight': 1,
                        'elements': [{
                            'tag': 'div',
                            'text': {
                                'tag': 'lark_md',
                                'content': '**事件**\n' + hook_event
                            }
                        }]
                    }
                ]
            },
            {'tag': 'hr'},
            {
                'tag': 'note',
                'elements': [{
                    'tag': 'plain_text',
                    'content': '\U0001f4c1 ' + cwd
                }]
            }
        ]
    }
}

body = json.dumps(card, ensure_ascii=False).encode('utf-8')
req = urllib.request.Request(webhook_url, data=body, headers={'Content-Type': 'application/json; charset=utf-8'}, method='POST')
try:
    resp = urllib.request.urlopen(req)
    result = json.loads(resp.read().decode('utf-8'))
    if result.get('code', -1) != 0:
        print('飞书通知发送失败:', result, file=sys.stderr)
        sys.exit(1)
except Exception as e:
    print('飞书通知发送失败:', e, file=sys.stderr)
    sys.exit(1)
" <<< "$STDIN_JSON"
