# Lark Interactive Card Notify Script for Claude Code Hooks
# This file is auto-generated by install-claude-notify-hooks skill.

import json
import os
import sys
import urllib.request

webhook_url = os.environ.get('LARK_WEBHOOK_URL', '')
event_type = os.environ.get('LARK_EVENT_TYPE', 'Stop')
stdin_json = os.environ.get('LARK_STDIN_DATA', '')

if not stdin_json:
    stdin_json = sys.stdin.read() if not sys.stdin.isatty() else '{}'

try:
    data = json.loads(stdin_json) if stdin_json.strip() else {}
except:
    data = {}

session_id = data.get('session_id', 'N/A')
cwd = data.get('cwd', 'N/A')
permission_mode = data.get('permission_mode', 'N/A')
hook_event = data.get('hook_event_name', event_type)
notification_type = data.get('notification_type', '')
message = data.get('message', '')
title_field = data.get('title', '')
reason = data.get('reason', '')
last_assistant_message = data.get('last_assistant_message', '')
error = data.get('error', '')
error_details = data.get('error_details', '')

project_name = os.path.basename(cwd) if cwd != 'N/A' else 'N/A'
short_session_id = session_id[:8] if len(session_id) > 8 else session_id

# Truncate long messages for card display
def truncate(text, max_len=500):
    if len(text) > max_len:
        return text[:max_len] + '...'
    return text

# Build message content block
def make_msg_block(label, text):
    if not text:
        return None
    return {
        'tag': 'div',
        'text': {
            'tag': 'lark_md',
            'content': '**' + label + '**\n' + truncate(text.strip())
        }
    }

# --- Determine theme, title, and primary content based on event ---

extra_elements = []

if hook_event == 'StopFailure':
    theme_color = 'red'
    title = '\U0001f6a8 Claude Code 运行异常'
    content = '<at id=all></at> API 调用失败'
    if error:
        content = '<at id=all></at> API 错误：' + error
    if error_details:
        extra_elements.append(make_msg_block('错误详情', error_details))
    if last_assistant_message:
        extra_elements.append(make_msg_block('错误信息', last_assistant_message))

elif hook_event == 'SubagentStop':
    theme_color = 'blue'
    title = '\U0001f916 Claude Code 子任务完成'
    content = '<at id=all></at> 请查看执行结果'
    if reason:
        content = '<at id=all></at> ' + reason
    if last_assistant_message:
        extra_elements.append(make_msg_block('执行结果', last_assistant_message))

elif hook_event == 'Stop':
    theme_color = 'blue'
    title = '\U0001f916 Claude Code 执行完毕'
    content = '<at id=all></at> 请查看执行结果'
    if reason:
        content = '<at id=all></at> ' + reason
    if last_assistant_message:
        extra_elements.append(make_msg_block('执行结果', last_assistant_message))

elif hook_event == 'Notification':
    if notification_type == 'permission_prompt':
        theme_color = 'orange'
        title = '\U0001f510 Claude Code 需要授权'
        content = '<at id=all></at> 请回到终端批准工具执行'
        if message:
            extra_elements.append(make_msg_block('权限消息', message))
    elif notification_type == 'idle_prompt':
        theme_color = 'orange'
        title = '⏳ Claude Code 等待响应'
        content = '<at id=all></at> 请回到终端继续操作'
        if message:
            extra_elements.append(make_msg_block('等待消息', message))
    elif notification_type == 'elicitation_dialog':
        theme_color = 'orange'
        title = '\U0001f4ac Claude Code 需要输入'
        content = '<at id=all></at> 请回到终端回答问题'
        if message:
            extra_elements.append(make_msg_block('问题', message))
    elif notification_type == 'elicitation_complete':
        theme_color = 'green'
        title = '\U0001f4ac Claude Code 交互完成'
        content = '<at id=all></at> 交互已完成'
        if message:
            extra_elements.append(make_msg_block('交互消息', message))
    elif notification_type == 'elicitation_response':
        theme_color = 'turquoise'
        title = '\U0001f4ac Claude Code 收到交互响应'
        content = '<at id=all></at> 已收到用户响应'
        if message:
            extra_elements.append(make_msg_block('响应内容', message))
    elif notification_type == 'auth_success':
        theme_color = 'green'
        title = '✅ Claude Code 认证成功'
        content = '认证已完成'
        if message:
            extra_elements.append(make_msg_block('认证消息', message))
    else:
        theme_color = 'orange'
        title = '\U0001f514 Claude Code 通知'
        content = '<at id=all></at> 请关注终端消息'
        if message:
            extra_elements.append(make_msg_block('通知内容', message))
else:
    theme_color = 'grey'
    title = '\U0001f514 Claude Code 事件'
    content = '<at id=all></at> ' + hook_event
    if message:
        extra_elements.append(make_msg_block('消息', message))

event_display = notification_type if notification_type else hook_event

# --- Build card elements ---

card_elements = [
    {
        'tag': 'div',
        'text': {
            'tag': 'lark_md',
            'content': '**' + content + '**'
        }
    }
]

# Add extra message elements (error details, assistant message, notification message)
for elem in extra_elements:
    if elem is not None:
        card_elements.append(elem)

card_elements.append({'tag': 'hr'})

# Info columns
card_elements.append({
    'tag': 'column_set',
    'flex_mode': 'bisect',
    'background_style': 'default',
    'columns': [
        {
            'tag': 'column',
            'width': 'weighted',
            'weight': 1,
            'elements': [{
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**项目**\n' + project_name
                }
            }]
        },
        {
            'tag': 'column',
            'width': 'weighted',
            'weight': 1,
            'elements': [{
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**会话**\n' + short_session_id
                }
            }]
        }
    ]
})

card_elements.append({
    'tag': 'column_set',
    'flex_mode': 'bisect',
    'background_style': 'default',
    'columns': [
        {
            'tag': 'column',
            'width': 'weighted',
            'weight': 1,
            'elements': [{
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**权限模式**\n' + permission_mode
                }
            }]
        },
        {
            'tag': 'column',
            'width': 'weighted',
            'weight': 1,
            'elements': [{
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**事件**\n' + event_display
                }
            }]
        }
    ]
})

card_elements.append({'tag': 'hr'})
card_elements.append({
    'tag': 'note',
    'elements': [{
        'tag': 'plain_text',
        'content': '\U0001f4c1 ' + cwd
    }]
})

card = {
    'msg_type': 'interactive',
    'card': {
        'header': {
            'title': {
                'tag': 'plain_text',
                'content': title
            },
            'template': theme_color
        },
        'elements': card_elements
    }
}

body = json.dumps(card, ensure_ascii=False).encode('utf-8')
req = urllib.request.Request(webhook_url, data=body, headers={'Content-Type': 'application/json; charset=utf-8'}, method='POST')
try:
    resp = urllib.request.urlopen(req)
    result = json.loads(resp.read().decode('utf-8'))
    if result.get('code', -1) != 0:
        print('Lark 通知发送失败:', result, file=sys.stderr)
        sys.exit(1)
except Exception as e:
    print('Lark 通知发送失败:', e, file=sys.stderr)
    sys.exit(1)
