# Lark Interactive Card Notify Script for Claude Code Hooks
# This file is auto-generated by install-claude-notify-hooks skill.
# Usage: py -3 lark-notify.py [Stop|StopFailure|Notification|SubagentStop] < stdin_json
#
# Claude Code 通过 stdin 传入会话 JSON，脚本解析后构建 Lark 交互式卡片并推送通知。
# 支持事件：Stop（执行完毕）、SubagentStop（子任务完成）、StopFailure（运行异常）、Notification（各类通知）

import json
import os
import sys
import urllib.request

# Webhook 地址，安装时由 skill 替换 __LARK_WEBHOOK_URL__ 为真实 URL
LARK_WEBHOOK_URL = "__LARK_WEBHOOK_URL__"

# 事件类型：通过命令行参数传入，作为 hook_event_name 的默认值
event_type = sys.argv[1] if len(sys.argv) > 1 else 'Stop'

# 从 stdin 读取 Claude Code 传入的会话 JSON（用 buffer 读取避免 Windows 代理对编码问题）
if not sys.stdin.isatty():
    stdin_json = sys.stdin.buffer.read().decode('utf-8', errors='replace')
else:
    stdin_json = '{}'

try:
    data = json.loads(stdin_json) if stdin_json.strip() else {}
except:
    data = {}

# 解析会话字段
session_id = data.get('session_id', 'N/A')
cwd = data.get('cwd', 'N/A')
permission_mode = data.get('permission_mode', 'N/A')
hook_event = data.get('hook_event_name', event_type)  # 优先使用 JSON 中的事件名
notification_type = data.get('notification_type', '')   # Notification 子类型
message = data.get('message', '')                       # Notification 消息正文
title_field = data.get('title', '')                     # Notification 标题
reason = data.get('reason', '')                         # Stop/StopFailure 原因
last_assistant_message = data.get('last_assistant_message', '')  # Stop 时 Claude 的最终回复
error = data.get('error', '')                           # StopFailure 错误类型
error_details = data.get('error_details', '')           # StopFailure 错误详情

# 用于卡片展示的简短标识
project_name = os.path.basename(cwd) if cwd != 'N/A' else 'N/A'
short_session_id = session_id[:8] if len(session_id) > 8 else session_id


def truncate(text, max_len=500):
    """截断过长文本，避免 Lark 卡片内容溢出"""
    if len(text) > max_len:
        return text[:max_len] + '...'
    return text


def make_msg_block(label, text):
    """构建 Lark 卡片的富文本消息块（加粗标签 + 内容），text 为空时返回 None"""
    if not text:
        return None
    return {
        'tag': 'div',
        'text': {
            'tag': 'lark_md',
            'content': '**' + label + '**\n' + truncate(text.strip())
        }
    }


# --- 根据事件类型确定卡片主题色、标题、主内容和附加消息块 ---

extra_elements = []

if hook_event == 'StopFailure':
    # API 调用失败：限流、认证、计费等，展示错误类型和详情
    theme_color = 'red'
    title = '\U0001f6a8 Claude Code 运行异常'
    content = '<at id=all></at> API 调用失败'
    if error:
        content = '<at id=all></at> API 错误：' + error
    if error_details:
        extra_elements.append(make_msg_block('错误详情', error_details))
    if last_assistant_message:
        extra_elements.append(make_msg_block('错误信息', last_assistant_message))

elif hook_event == 'SubagentStop':
    # 子任务执行完毕：展示子任务结果摘要
    theme_color = 'blue'
    title = '\U0001f916 Claude Code 子任务完成'
    content = '<at id=all></at> 请查看执行结果'
    if reason:
        content = '<at id=all></at> ' + reason
    if last_assistant_message:
        extra_elements.append(make_msg_block('执行结果', last_assistant_message))

elif hook_event == 'Stop':
    # 主代理执行完毕：展示 Claude 最终回复摘要
    theme_color = 'blue'
    title = '\U0001f916 Claude Code 执行完毕'
    content = '<at id=all></at> 请查看执行结果'
    if reason:
        content = '<at id=all></at> ' + reason
    if last_assistant_message:
        extra_elements.append(make_msg_block('执行结果', last_assistant_message))

elif hook_event == 'Notification':
    # 各类通知：根据 notification_type 细分场景，展示对应的 message 内容
    if notification_type == 'permission_prompt':
        # 需要用户批准工具执行权限
        theme_color = 'orange'
        title = '\U0001f510 Claude Code 需要授权'
        content = '<at id=all></at> 请回到终端批准工具执行'
        if message:
            extra_elements.append(make_msg_block('权限消息', message))
    elif notification_type == 'idle_prompt':
        # Claude 处于空闲状态，等待用户输入
        theme_color = 'orange'
        title = '⏳ Claude Code 等待响应'
        content = '<at id=all></at> 请回到终端继续操作'
        if message:
            extra_elements.append(make_msg_block('等待消息', message))
    elif notification_type == 'elicitation_dialog':
        # 弹出交互对话框，需要用户回答问题
        theme_color = 'orange'
        title = '\U0001f4ac Claude Code 需要输入'
        content = '<at id=all></at> 请回到终端回答问题'
        if message:
            extra_elements.append(make_msg_block('问题', message))
    elif notification_type == 'elicitation_complete':
        # 交互对话框已关闭
        theme_color = 'green'
        title = '\U0001f4ac Claude Code 交互完成'
        content = '<at id=all></at> 交互已完成'
        if message:
            extra_elements.append(make_msg_block('交互消息', message))
    elif notification_type == 'elicitation_response':
        # 收到用户的交互响应
        theme_color = 'turquoise'
        title = '\U0001f4ac Claude Code 收到交互响应'
        content = '<at id=all></at> 已收到用户响应'
        if message:
            extra_elements.append(make_msg_block('响应内容', message))
    elif notification_type == 'auth_success':
        # 认证成功（如 OAuth 登录完成）
        theme_color = 'green'
        title = '✅ Claude Code 认证成功'
        content = '认证已完成'
        if message:
            extra_elements.append(make_msg_block('认证消息', message))
    else:
        # 未识别的通知类型，兜底处理
        theme_color = 'orange'
        title = '\U0001f514 Claude Code 通知'
        content = '<at id=all></at> 请关注终端消息'
        if message:
            extra_elements.append(make_msg_block('通知内容', message))
else:
    # 未识别的事件类型，兜底处理
    theme_color = 'grey'
    title = '\U0001f514 Claude Code 事件'
    content = '<at id=all></at> ' + hook_event
    if message:
        extra_elements.append(make_msg_block('消息', message))

# 用于卡片信息栏显示的事件标识
event_display = notification_type if notification_type else hook_event

# --- 组装 Lark 交互式卡片 ---

card_elements = [
    # 主内容区：@所有人 + 核心提示
    {
        'tag': 'div',
        'text': {
            'tag': 'lark_md',
            'content': '**' + content + '**'
        }
    }
]

# 附加消息块：错误详情、执行结果、权限消息等
for elem in extra_elements:
    if elem is not None:
        card_elements.append(elem)

card_elements.append({'tag': 'hr'})

# 信息栏：项目名称 / 会话ID
card_elements.append({
    'tag': 'column_set',
    'flex_mode': 'bisect',
    'background_style': 'default',
    'columns': [
        {
            'tag': 'column',
            'width': 'weighted',
            'weight': 1,
            'elements': [{
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**项目**\n' + project_name
                }
            }]
        },
        {
            'tag': 'column',
            'width': 'weighted',
            'weight': 1,
            'elements': [{
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**会话**\n' + short_session_id
                }
            }]
        }
    ]
})

# 信息栏：权限模式 / 事件类型
card_elements.append({
    'tag': 'column_set',
    'flex_mode': 'bisect',
    'background_style': 'default',
    'columns': [
        {
            'tag': 'column',
            'width': 'weighted',
            'weight': 1,
            'elements': [{
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**权限模式**\n' + permission_mode
                }
            }]
        },
        {
            'tag': 'column',
            'width': 'weighted',
            'weight': 1,
            'elements': [{
                'tag': 'div',
                'text': {
                    'tag': 'lark_md',
                    'content': '**事件**\n' + event_display
                }
            }]
        }
    ]
})

# 底部备注：工作目录
card_elements.append({'tag': 'hr'})
card_elements.append({
    'tag': 'note',
    'elements': [{
        'tag': 'plain_text',
        'content': '\U0001f4c1 ' + cwd
    }]
})

# 完整卡片结构
card = {
    'msg_type': 'interactive',
    'card': {
        'header': {
            'title': {
                'tag': 'plain_text',
                'content': title
            },
            'template': theme_color
        },
        'elements': card_elements
    }
}

# 发送 HTTP POST 请求到 Lark Webhook
body = json.dumps(card, ensure_ascii=False).encode('utf-8')
req = urllib.request.Request(LARK_WEBHOOK_URL, data=body, headers={'Content-Type': 'application/json; charset=utf-8'}, method='POST')
try:
    resp = urllib.request.urlopen(req)
    result = json.loads(resp.read().decode('utf-8'))
    if result.get('code', -1) != 0:
        print('Lark 通知发送失败:', result, file=sys.stderr)
        sys.exit(1)
except Exception as e:
    print('Lark 通知发送失败:', e, file=sys.stderr)
    sys.exit(1)
