#!/bin/bash
# Lark Interactive Card Notify Script for Claude Code Hooks
# This file is auto-generated by install-claude-notify-hooks skill.
# Shell wrapper that delegates to Python for UTF-8 safe JSON and HTTP.

export LARK_WEBHOOK_URL="__LARK_WEBHOOK_URL__"
export LARK_EVENT_TYPE="${1:-Stop}"

# Read stdin and pass to Python via env to avoid bash pipe encoding issues on Windows
export LARK_STDIN_DATA=$(cat)

py -3 "$(dirname "$0")/lark-notify.py"
